### ISSUE TITLE
Use cases without syntax errors that fail tests should not be abandoned

### ISSUE THREAD

**Issue by iejzh** [Codium-ai/cover-agent#103]
When a use case run fails, is it a problem with the code under test or the test case? Something to consider.

**Comment by EmbeddedDevops1** [comment]
Excellent question. We don't differentiate right now because the whole purpose of Cover Agent (as of now) is to provide working tests for regressions.

We'd love your feedback on how to improve Cover Agent and find ways to tell the user that their "code is broken." Any suggestions?
