### ISSUE TITLE
Azure OpenAI auth

### ISSUE THREAD

**Issue by aleixvilaseca** [Codium-ai/cover-agent#104]
Hello,
I am trying to use Azure OpenAI to run the agent but this is not possible for me because I have to add a key and endpoint for it to work properly. Everything works correctly when I set the variable with the openAI token (sk-xx-xxxx), but it is impossible for me to do it from Azure OPenAI. Any recommendations? Is there a way to do it?

Thanks!

**Comment by betnevs** [comment]
You can set Azure OpenAI endpoint and key in system environment, for example:

```
export AZURE_API_KEY=my-api-key
export AZURE_API_BASE=my-api-base
export AZURE_API_VERSION=2024-02-01
```

Then run your command，the underlying code uses [LiteLLM](https://docs.litellm.ai/) to do the transformation.

**Comment by EmbeddedDevops1** [comment]
Thanks @betnevs!
