### ISSUE TITLE
cannot parse Jacoco XML file

### ISSUE THREAD

**Issue by ramsey-coding** [Codium-ai/cover-agent#107]
The given code cannot even parse the Jacoco XML file

**Comment by EmbeddedDevops1** [comment]
If you look at our [nightly integration test file](https://github.com/Codium-ai/cover-agent/blob/main/tests_integration/test_all.sh) you'll notice that we currently only support CSV Jacoco file outputs (as @davidparry graciously contributed the coverage support and sample project to the repo). 

If you could open up a PR and [add support for XML parsing](https://github.com/Codium-ai/cover-agent/blob/main/cover_agent/CoverageProcessor.py) that would be amazing. Thanks!

**Comment by davidparry** [comment]
What is the intent for the xml parsing?

**Comment by EmbeddedDevops1** [comment]
@davidparry I suppose because people may specifically want an XML output versus CSV? @ramsey-coding can you weigh in on this?

**Comment by EmbeddedDevops1** [comment]
Going to close out this issue. Feel free to open it back up if you want to open up a PR with XML parsing support.
