### ISSUE TITLE
How to Compile cover-agent-ubuntu Binary from Source Code?

### ISSUE THREAD

**Issue by SiriusHsh** [Codium-ai/cover-agent#110]
Hello,

I am having trouble running the `cover-agent-ubuntu`  binary file downloaded from the releases section on Ubuntu 18.04. The error I encounter is GLIBC_2.35 not found.

The cover agent installed via pip runs correctly in the Python environment, but it causes conflicts with other Python packages in my project, preventing my other projects from running properly. To resolve this issue, I would like to use the binary file instead.

Could you please provide guidance on how to compile the `cover-agent-ubuntu` binary from the source code?

Thank you!

**Comment by EmbeddedDevops1** [comment]
Yes. Just run `make installer`. I updated the README.md as well. Thanks for bringing this up!
