### ISSUE TITLE
Support for Using a Local LLM Instead of OpenAI for Enhanced Security

### ISSUE THREAD

**Issue by EyalPery** [Codium-ai/cover-agent#115]
It would be highly beneficial to have the option to integrate Cover Agent with a local LLM instead of sending data to the OpenAI API. This feature would enhance security and data privacy for users who handle sensitive information.

Thanks!

**Comment by mrT23** [comment]
@EyalPery 
you can definitely do that. We support litellm:
https://github.com/Codium-ai/cover-agent?tab=readme-ov-file#using-other-llms

For example, use ollama:
https://litellm.vercel.app/docs/providers/ollama

Make sure to use high-quality **code** model.
