### ISSUE TITLE
Complicated projects have a deep invocation structure. Is there a good solution to generate a UT?

### ISSUE THREAD

**Issue by niuzhi** [Codium-ai/cover-agent#117]
At present, this tool can get good results in the test case coverage of simple files. However, if it is a complicated project, there is a deep function invocation structure. Is there a good solution?If all packets are injected into the LLM, the system prompts that the token exceeds the limit.

**Comment by EmbeddedDevops1** [comment]
Yes, this, indeed, is a huge challenge not only for Cover Agent but anyone using LLMs for test generation (and something we're actively trying to solve).

The easiest workaround (though no ideal) would be to utilize the `--additional-instructions` and `--included-files` options. To limit the token count you can create a new file that contains just the functions needed for context. Alternatively you can copy and paste the relevant code and add it to `--additional-instructions`.

If you have any other suggestions please feel free to post here or, better yet, submit a PR for any new ideas you may have. In the mean time I'm going to close this Issue but feel free to re-open it if necessary. Thanks.

**Comment by ramsey-coding** [comment]
@EmbeddedDevops1 you mentioned that including additional files are not optimal. So what is ideal?

**Comment by EmbeddedDevops1** [comment]
@ramsey-coding an automated way to pick out, intelligently, what files are needed and provide it as context. Think of a RAG model that’s really really good.

**Comment by ramsey-coding** [comment]
@EmbeddedDevops1 RAG based on what criteria to chose?

**Comment by EmbeddedDevops1** [comment]
> @EmbeddedDevops1 RAG based on what criteria to chose from?

The context depends on what you’re trying to do but including any relevant imports is a good start.
