### ISSUE TITLE
relevant_line_number_to_insert_tests_after restoring for rolling back cases

### ISSUE THREAD

**Issue by Maxwell-FreeFOV** [Codium-ai/cover-agent#129]
The relevant_line_number_to_insert_tests_after value may increase if new tests are inserted:

self.relevant_line_number_to_insert_tests_after += len(
                        additional_imports_lines
                    )  # this is important, otherwise the next test will be inserted at the wrong line

However, this value may need to be restored if the tests are rolled back.

**Comment by EmbeddedDevops1** [comment]
@Maxwell-FreeFOV are you proposing a change to the code? If so, any change you can open a PR and we'll investigate ASAP?

**Comment by EmbeddedDevops1** [comment]
@Maxwell-FreeFOV Do you have an example of where this is failing to warrant the change?

**Comment by EmbeddedDevops1** [comment]
We just [issued a fix for the line insertion bug](https://github.com/Codium-ai/cover-agent/pull/149). Please have a look and if the issue persists feel free to re-open the issue. Thanks.
