### ISSUE TITLE
how to user local huggingface version model

### ISSUE THREAD

**Issue by hgcdanniel** [Codium-ai/cover-agent#136]
How could I use my own SFT model or local hugging face model

**Comment by EmbeddedDevops1** [comment]
Hi @hgcdanniel. Please take a look at the [LLM section in the README](https://github.com/Codium-ai/cover-agent/blob/main/README.md#using-other-llms). You'll see there's a link to a [LiteLLM page demonstrating how to get set up with HuggingFace and the like](https://litellm.vercel.app/docs/proxy/quick_start#supported-llms).
