### ISSUE TITLE
Feature Request: Support Locally Running LLM

### ISSUE THREAD

**Issue by gklein** [Codium-ai/cover-agent#15]
Support the use of locally running LLMs using LiteLLM or directly for Ollama users. 
Enabling locally running LLMs will allow companies to use cover-agent without sending any code outside of the organization.

**Comment by EmbeddedDevops1** [comment]
@gklein This is a great idea. I've tested these prompts with Code Llama and haven't been able to achieve the level of quality in response or code (albeit it wasn't the most powerful version of Code Llama).

You can generate just the prompt without ever hitting OpenAPI's servers by using the `--prompt-only` option when calling `cover-agent`. 

Would you be willing to take the output from `generated_prompt.md` and plug it into models that you'd like to see support with? If you could share the response that would be extremely helpful to see what the delta would be between GPT and other LLMs.

**Comment by mrT23** [comment]
@coditamar @EmbeddedDevops1 
i will take this.

No reason not to use LiteLLM
