### ISSUE TITLE
Working of C#

### ISSUE THREAD

**Issue by Ajaykumarkv17** [Codium-ai/cover-agent#153]
Hiii I have a issue in running with C# Projects 

Can you please give me a proper cover-agent command so that i can use it 

I need a sample command like this for c#

cover-agent \
  --model "claude-3-5-sonnet-20240620"
  --source-file-path "templated_tests/python_fastapi/app.py" \
  --test-file-path "templated_tests/python_fastapi/test_app.py" \
  --code-coverage-report-path "templated_tests/python_fastapi/coverage.xml" \
  --test-command "pytest --cov=. --cov-report=xml --cov-report=term" \
  --test-command-dir "templated_tests/python_fastapi" \
  --coverage-type "cobertura" \
  --desired-coverage 70 \
  --max-iterations 5

**Comment by EmbeddedDevops1** [comment]
Hi. C# is part of our nightly regression pipeline. We call Cover Agent against it from [here](https://github.com/Codium-ai/cover-agent/blob/main/tests_integration/test_all.sh#L68-L76). The example project code can be found [here](https://github.com/Codium-ai/cover-agent/tree/main/templated_tests/csharp_webservice).

**Comment by Ajaykumarkv17** [comment]
Is this work in windows but i could not run it properly 
Please give me the command in windows it is very helpful

**Comment by Ajaykumarkv17** [comment]
Please give me the updated windows solution

**Comment by EmbeddedDevops1** [comment]
Hi,

Can you post the command you ran and the error you're getting?
