### ISSUE TITLE
Generate Tests for a Directory

### ISSUE THREAD

**Issue by shivendrasoni** [Codium-ai/cover-agent#16]
Right now, we have to give the source file path for which it generates tests, doing this it would be difficult to run for larger repos. 

How can I run it for the entire directory, where it goes in, finds source files and writes tests?

**Comment by EmbeddedDevops1** [comment]
## Update
Take a look at the [README under the integration tests folder](https://github.com/Codium-ai/cover-agent/tree/main/tests_integration#increasing-coverage-iteratively). I created a small utility [Python script](https://github.com/Codium-ai/cover-agent/blob/main/tests_integration/increase_coverage.py) to iterate over all source files (and their respective tests) to increase the coverage of this repo.

It's not automatic but a step in the right direction.
