### ISSUE TITLE
Added test framework and proper error messaging in prompt

### ISSUE THREAD

**Issue by EmbeddedDevops1** [Codium-ai/cover-agent#160]
The prompt to the LLM doesn't contain the test framework and the error message is not always handled correctly (see `tests_integration/increase_coverage.py` outputs as an example).

Add the test framework and update the error message output to include meaningful errors from the offending code.

**Comment by miguellords** [comment]
download
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive
