### ISSUE TITLE
Refactor main to allow utility Python scripts to call it

### ISSUE THREAD

**Issue by EmbeddedDevops1** [Codium-ai/cover-agent#19]
## Background
`cover_agent/main.py` is currently architected in a way that each source/test file pair must be called from the command line. THere is demand for an intelligent crawler that can figure out which test file maps to which source file. Once we have a list that maps out source to test file we should be able to pass that into a `CoverAgent` class object and run it just as we would run `cover-agent` from the command line.

## Task
Refactor `cover_agent/main.py`'s `main()` by turning it into `__init__()` that takes in the `parse_args()` return object as a parameter (or all arguments individually). `main.py` should now become `CoverAgent.py` and declared as a Python class with the name `CoverAgent`. `tests/test_main.py` will also have to be updated accordingly.

## Acceptance Criteria
1. User will be able to import the `cover_agent` package (after a `pip install`) and call multiple iterations against multiple source/test files all within a single Python script without have to use the command line.
2. `tests/test_main.py` now become `tests/test_CoverAgent.py`
3. References to `cover_agent/main.py` (i.e. in `.github/workflows/ci_pipeline.yml`, `pyproject.toml`, and `README.md`) now refer to the `CoverAgent` class.
4. `README.md` has a new section containing how to import and use the `CoverAgent` class to programmatically increase test coverage for multiple files within the user's repository.

**Comment by Umpire2018** [comment]
> THere is demand for an intelligent crawler that can figure out which test file maps to which source file. 

Using a Python project as an example, we can use static analysis tools like [Abstract Syntax Trees](https://docs.python.org/3/library/ast.html) or [tree-sitter](https://tree-sitter.github.io/tree-sitter/) to analyze the relationships between functions/classes and their references. This process is not that simple from what i have learned but i can give it a shot.

Alternatively, we can use conventional methods like matching by file name, class name, or function name. 

Perhaps we should focus on finalizing the parsing and mapping process first before considering how to integrate and apply these results into the project workflow to automate the process of running tests and generating coverage reports.

**Comment by amahpour** [comment]
Hey @Umpire2018 thanks for the contribution. Yeah, AST works great. I added to use as a parsing engine for Python. The only challenge is that we’d have to implement this language by language. I guess that’s not a bad thing but just something to think about in terms of overhead and maintainability.

**Comment by Umpire2018** [comment]
> AST works great. The only challenge is that you’d have to implement this language by language. I guess that’s not a bad thing but just something to think about in terms of overhead and maintainability.

I seconded with you. Using `AST` may not be a good choice. 

I learned that the project is currently using `ast`

https://github.com/Codium-ai/cover-agent/blob/3b09281d749542b07dbbc389a703fa8a25678964/cover_agent/FilePreprocessor.py#L36-L49

Maybe use [tree-sitter](https://tree-sitter.github.io/tree-sitter/) to process multiple language?
