### ISSUE TITLE
Can't run unless repo already has tests and a coverage file

### ISSUE THREAD

**Issue by tyler-suard-parker** [Codium-ai/cover-agent#21]
It would be nice to have a plug-and-play solution for repos with no pre-existing tests or coverage files.

**Comment by EmbeddedDevops1** [comment]
Great feedback. This is something actually already exists with the [Codiumate extension](https://www.codium.ai/) along with a myriad of other features.

If you are dead set on just using Cover Agent you can actually "cheat" the AI by creating an empty test file with some imports that you expect it to use. For example, if you're working in Python you can create a test file that looks like this:
```
import pytest
import json
import requests

# Nothing else to see here folks.
```

If you want to go crazy you can add a nonsense test function as well and remove it later:
```
import pytest
import json
import requests

def test_nothing_to_see_here_folks():
    assert True
```

**Comment by matbee-eth** [comment]
What exactly is a coverage file? The project says it works with any language but its expecting XML?

**Comment by Umpire2018** [comment]
@EmbeddedDevops1 I am thinking adding default settings for this scenario, what do you think?

```python
    parser.add_argument(
        "--test-file-path", required=True, help="Path to the input test file."
    )
    parser.add_argument(
        "--code-coverage-report-path",
        required=True,
        help="Path to the code coverage report file.",
    )
```

**Comment by tyler-suard-parker** [comment]
@Umpire2018 I would recommend adding custom errors as well, with instructions on how to create a test file and a coverage file.  Even better, just make a script that checks for test and coverage files, and if none are available, the script creates a test and coverage file.  Many people don't even know what a coverage file is.

**Comment by EmbeddedDevops1** [comment]
@tyler-suard-parker Unfortunately code coverage metrics are a prerequisite for the project itself. 

The [TestGen-LLM paper](https://arxiv.org/abs/2402.09171) from Meta (what this project is [based off of](https://www.codium.ai/blog/we-created-the-first-open-source-implementation-of-metas-testgen-llm/)) requires you to generate a code coverage report so it knows which lines are missing coverage and need tests.

Each language and test environment is different so it's pretty hard to back in test generation/code coverage commands for every single environment and language.

💡 Tip: A quick prompt of "how to generate a Cobertura code coverage report and test template" to your favorite LLM should do the trick 😄.
