### ISSUE TITLE
AssertionError: Fatal: The coverage report file was not updated after the test command. file_mod_time_ms: 1716321605810, time_of_test_command: 1716321611774. False

### ISSUE THREAD

**Issue by tyler-suard-parker** [Codium-ai/cover-agent#22]
AssertionError: Fatal: The coverage report file was not updated after the test command. file_mod_time_ms: 1716321605810, time_of_test_command: 1716321611774. False

Command run:

cover-agent --source-file-path "autogen_.py" --test-file-path "tests/test_autogen_.py" --code-coverage-report-path "coverage.cov" --test-command "pytest -s tests/test_autogen_.py" --test-command-dir "." --coverage-type "cobertura" --desired-coverage 80 --max-iterations 10

**Comment by EmbeddedDevops1** [comment]
Thanks for raising the issue. Based on your `--test-command` parameter it looks like you're running `pytest` without generating an XML coverage report (which is the current filetype we support today - hopefully more coming soon). You'll need to generate an XML style code coverage report (e.g. `--cov-report=xml:cobertura.xml`) and then point that that coverage file.

I'll keep this issue open to update the docs and/or support raw `.cov` files. Even better if you'd be willing to open up a PR and contribute back! 😄

**Comment by tyler-suard-parker** [comment]
The readme contains no instructions about generating a coverage report before running.
