### ISSUE TITLE
How to use litellm by OpenAI Compatible Endpoint？

### ISSUE THREAD

**Issue by quarechen** [Codium-ai/cover-agent#32]
How to use litellm by OpenAI Compatible Endpoint？

**Comment by mrT23** [comment]
https://litellm.vercel.app/docs/providers/openai_compatible

**Comment by quarechen** [comment]
> https://litellm.vercel.app/docs/providers/openai_compatible

but how can I use it with cmd？
![image](https://github.com/Codium-ai/cover-agent/assets/30918026/cc3e3c94-0649-4639-ad85-5cedbd7391b2)

**Comment by mrT23** [comment]
you haven't specified which model/framework, but basically you need to give the correct model name and api_base

```
export API_KEY = ...

--model="openai/mistral" 
--api-base=http://localhost:11434"
```

to run:

![image](https://github.com/Codium-ai/cover-agent/assets/21198860/540f14f2-7be1-45e9-9c72-8185a4fcd3b2)

**Comment by quarechen** [comment]
> you haven't specified which model/framework, but basically you need to give the correct model name and api_base您还没有指定哪个模型/框架，但基本上您需要提供正确的模型名称和 api_base
> 
> ```
> export API_KEY = ...
> 
> --model="openai/mistral" 
> --api-base=http://localhost:11434"
> ```
> 
> to run: 跑步：
> 
> ![image](https://private-user-images.githubusercontent.com/21198860/333062928-540f14f2-7be1-45e9-9c72-8185a4fcd3b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDYwNDUsIm5iZiI6MTcxNjQ0NTc0NSwicGF0aCI6Ii8yMTE5ODg2MC8zMzMwNjI5MjgtNTQwZjE0ZjItN2JlMS00NWU5LTljNzItODE4NWE0ZmNkM2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA2MjkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZjYzNDIyMGU4YzU2MzQwNzY4NjdkZGIwYjI4ODRlNzEyZmJhZmI0MTQzZWM4OTI4NGRjNWEyYjI1NmU0ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aCpuC20F01B75CTl3knI4-vHardbU22P7xZmpuFD16k)

it does not work:
![image](https://github.com/Codium-ai/cover-agent/assets/30918026/4285a3f0-5da9-42f5-b1ba-600c5add7cdd)
![image](https://github.com/Codium-ai/cover-agent/assets/30918026/793109ca-b55e-4a53-bcb9-a4f0727b2293)

**Comment by mrT23** [comment]
update the repo !

![image](https://github.com/Codium-ai/cover-agent/assets/21198860/955d9029-9fda-4149-8a28-7ffcdc34f41f)

**Comment by mullerjohn** [comment]
To use litellm by OpenAI with a compatible endpoint, you need to integrate the API with your application, enabling natural language processing capabilities. For editing short videos, you can use the [capcuttemplat ](https://capcuttemplate.live/)feature to streamline the video editing process, making it easier to apply templates and automate editing tasks through the language model.
