### ISSUE TITLE
Java file support

### ISSUE THREAD

**Issue by rostalgen** [Codium-ai/cover-agent#38]
Although Jacaco isn't supported, I was able to get around it by converting it to cobertura. cover-agent correctly handles the coverage report and is able to generate the tests, but the test ends up appended to the _end_ of the Java file, after the closing brace, and therefore the compile/test fails.

cover-agent   --source-file-path "src/main/java/com/SampleService.java"   --test-file-path "src/test/java/com/SampleServiceTest.java"   --code-coverage-report-path "build/cobertura.xml"   --test-command "./gradlew cleanTest test --tests "com.SampleServiceTest" && python3 ~/cover2cover.py build/reports/jacoco/test/jacocoTestReport.xml src/main/java/ > build/cobertura.xml"    --desired-coverage 90   --max-iterations 1

Example SampleServiceTest.java snippet

```
public class SampleServiceTest {
  ...
  @Test
  public void existingTest()
  {
    // existingTest
  }
} // end of class
// code after here is invalid and breaks compile

@Test
public void coverCreatedTest() {
  // cover created test
}
```

024-05-23 08:27:49,510 - cover_agent.UnitTestGenerator - ERROR - Test failed. Rolling back
2024-05-23 08:27:49,510 - cover_agent.main - INFO - Reached maximum iteration limit without achieving desired coverage.

**Comment by mrT23** [comment]
@rostalgen i do plan to engage this this week, see:
https://github.com/Codium-ai/cover-agent/issues/39

just for me to understand:

a code like this is invalid in Java (with additional class generated) ?

```
public class SampleServiceTest {
  ...
  @Test
  public void existingTest()
  {
    // existingTest
  }
} // end of class


// new generated test class
public class SampleServiceTestNew {
  @Test
  public void coverCreatedTest() {
    // cover created test
  }
}
```

**Comment by rostalgen** [comment]
Thanks for looking into this! While that code is legal, the new class would not have access to private methods written in the original class, which is often a pattern for common setup steps. I noticed that in my generated tests, these existing setup methods were used correctly, but would not work if added to a separate class. For example, the below would _not_ compile.

```
public class SampleServiceTest {
  ...
  @Test
  public void existingTest()
  {
    setupSomething();
    // existingTest
  }

  private void setupSomething()
  {
    // do setup
  }
} // end of class


// new generated test class
public class SampleServiceTestNew {
  @Test
  public void coverCreatedTest() {
    setupSomething(); // would be compile error
    // cover created test
  }
}
```

**Comment by EmbeddedDevops1** [comment]
@rostalgen, @davidparry add [this PR](https://github.com/Codium-ai/cover-agent/pull/62) and we merged it a few days ago to support Java + Jacoco.

Does that PR (and updates to the LLM calls in `main`) get you most of the way there or are you still not able to get tests generated properly?

**Comment by davidparry** [comment]
I am now able to get tests, works like a charm. Check out my docker image https://hub.docker.com/r/davidparry/cover-agent-ubuntu-aarch64 if you want to see it in action.

**Comment by rostalgen** [comment]
I pulled the latest code, but something still isn't working quite right. Atleast in my case, the tests continue to fail due to compilation issues.

I think the imports are being added right at the top of the file, but the first line must be that package line.

Is there a way to retain the updated test file so it can be inspected after the run?

i.e. 
Valid:
```
package com.some.package

import new.import.from.test
```

invalid:
```
import new.import.from.test

package com.some.package
```

**Comment by ajt001** [comment]
> I pulled the latest code, but something still isn't working quite right. Atleast in my case, the tests continue to fail due to compilation issues.
> 
> I think the imports are being added right at the top of the file, but the first line must be that package line.
> 
> Is there a way to retain the updated test file so it can be inspected after the run?
> 
> i.e. Valid:
> 
> ```
> package com.some.package
> 
> import new.import.from.test
> ```
> 
> invalid:
> 
> ```
> import new.import.from.test
> 
> package com.some.package
> ```

I also get the issue where the created tests are outside the last brace in the code, causing the compilation issue.

**Comment by mrT23** [comment]
> > I pulled the latest code, but something still isn't working quite right. Atleast in my case, the tests continue to fail due to compilation issues.
> > I think the imports are being added right at the top of the file, but the first line must be that package line.
> > Is there a way to retain the updated test file so it can be inspected after the run?
> > i.e. Valid:
> > ```
> > package com.some.package
> > 
> > import new.import.from.test
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > invalid:
> > ```
> > import new.import.from.test
> > 
> > package com.some.package
> > ```
> 
> I also get the issue where the created tests are outside the last brace in the code, causing the compilation issue.

Are you sure you use the latest code ? 

share your run command, and the logs

**Comment by ajt001** [comment]
> > > I pulled the latest code, but something still isn't working quite right. Atleast in my case, the tests continue to fail due to compilation issues.
> > > I think the imports are being added right at the top of the file, but the first line must be that package line.
> > > Is there a way to retain the updated test file so it can be inspected after the run?
> > > i.e. Valid:
> > > ```
> > > package com.some.package
> > > 
> > > import new.import.from.test
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > invalid:
> > > ```
> > > import new.import.from.test
> > > 
> > > package com.some.package
> > > ```
> > 
> > 
> > I also get the issue where the created tests are outside the last brace in the code, causing the compilation issue.
> 
> Are you sure you used the latest code ?
> 
> Share your run command, and the logs

` $ cover-agent \
--source-file-path "src/main/java/io/seraco/Utils.java" \
--test-file-path "src/test/java/TestUtils.java" \
--code-coverage-report-path "build/reports/kover/xml/report.xml" \
--test-command "gradle clean test koverXmlReport" \
--test-command-dir "./" \
--coverage-type "cobertura" \
--desired-coverage 80 \
--max-iterations 1 \
--model "ollama/codestral"`

Failures:

`/Users/andrew/tech/gh-other/1.0/src/test/java/TestUtils.java:24: error: unnamed classes are a preview feature and are disabled by default.
  void testDaysBetweenDifferentMonthsYears() {
  ^
  (use --enable-preview to enable unnamed classes)
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 800ms`

**Comment by mrT23** [comment]
(1)
use gpt4 

"ollama/codestral" is an open source model, and not a very good one
https://pr-agent-docs.codium.ai/finetuning_benchmark/ 

(2)
also, if you have already a prev  git installation, 'pip install git+https://github.com/Codium-ai/cover-agent.git' will do nothing. use --force

(3) see here:
https://github.com/Codium-ai/cover-agent/pull/82

With an updated version and a good code model, the import issue should be solved

**Comment by ajt001** [comment]
I'll give it a try then, thanks.

**Comment by ajt001** [comment]
@mrT23 Hi.
To confirm the issue isn't related to import statements, rather the unit tests are being placed after the last bracket, which causes the tests to fail.

I have the latest code (never had a version before current). 
So after doing above, it fails because of this: `relevant_line_number_to_insert_tests_after` variable (not the import variable).

**Comment by mrT23** [comment]
are you using GPT4 ?

**Comment by ajt001** [comment]
Using deepseek now based on the link you sent previously. Should it work? Seems not??

cover-agent \
--source-file-path "src/main/kotlin/Utils.kt" \
--test-file-path "src/test/kotlin/TestUtils.kt" \
--code-coverage-report-path "build/reports/kover/xml/report.xml" \
--test-command "gradle clean koverXmlReport" \
--test-command-dir "./" \
--coverage-type "cobertura" \
--desired-coverage 80 \
--max-iterations 1 \
--model "openai/deepseek-coder" \
--api-base "https://api.deepseek.com"

**Comment by mrT23** [comment]
open-source models are dramatically inferior in code to GPT4.
they may work, and may not, since they fail to understand and obey the prompt instructions.

If GPT4 will not work, that its a problem that we will address.

**Comment by EmbeddedDevops1** [comment]
All Java-LLM specific issues should now be resolved. We have integrated two different types of Java projects in our [nightly regression tests as well](https://github.com/Codium-ai/cover-agent/blob/main/tests_integration/README.md).
