### ISSUE TITLE
Make the test generation great (2) - handling of new imports

### ISSUE THREAD

**Issue by mrT23** [Codium-ai/cover-agent#40]
**what:**

we want to allow new tests to add additional imports and dependencies, if needed, that weren't a part of the original test file

**How:**

- generate with structured output an additional code that includes the import commands.
- also generate the relevant line number (usually line 1, but there are exceptions) where we need to push those imports

**Comment by Umpire2018** [comment]
Hi there, could you be more specific? I am a junior Python engineer with some knowledge of AI agents, and I would like to contribute to the project.

:)
