### ISSUE TITLE
Kindly someone help me with this.

### ISSUE THREAD

**Issue by TaisieNitta** [Codium-ai/cover-agent#47]
public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        
        System.out.println("Enter first string (s1): ");
        String s1 = scanner.nextLine();
        
        System.out.println("Enter second string (s2): ");
        String s2 = scanner.nextLine();
        
        int distance = calculateFientDistance(s1, s2);
        
        System.out.println("The Fient Distance between the two strings is: " + distance);
        
        scanner.close();
    }

This is the program to calculate the fient distance 
e.g. s1 = abcd
        s2 = abcd
    a-a=0
same for all

e.g.2 s1 = abcd
           s2 = efgh
|a-e| = 4
|b-f| = 4
|c-g| = 4
|d-h| = 4

4+4+4+4 = 16

e.g. s1 = abcd
s2 = ab
a-a=0
b-b=0
c-0=3
d-0=4

**Comment by osheitchang** [comment]
Hi can you specify what do you need help with?

**Comment by TaisieNitta** [comment]
> Hi can you specify what do you need help with?

Actually the given program is to find fient distance.
And it is working well when string of equal length is given 
Like [abcd] and [efgh]
For which I used ASCII code.
But when you input [abcd] and [ab]
Rather than giving the output 7 it gives 199, which is the sum of the ASCII code c = 99, d = 100
c+d = 199
But I want it should add like c is on 3rd place (in alphabetical order)
                                                  d is on 4th place (in alphabetical order)
So c+d = 7
I hope you will understand.
You may dry run the program using the given description.

**Comment by wassupjay** [comment]
The issue arises when the strings have different lengths, and the program is not handling it correctly. 
You can modify the calculateFientDistance method to handle strings of different lengths:

public static int calculateFientDistance(String s1, String s2) {
    int distance = 0;
    int len1 = s1.length();
    int len2 = s2.length();
    int minLen = Math.min(len1, len2);
    for (int i = 0; i < minLen; i++) {
        distance += Math.abs(s1.charAt(i) - s2.charAt(i));
    }
    distance += Math.abs(len1 - len2);
    return distance;}

**Comment by Debshibraj123** [comment]
hey  you can try this one

public static int calculateFientDistance(String s1, String s2) {
    int distance = 0;
    int len1 = s1.length();
    int len2 = s2.length();
    int minLen = Math.min(len1, len2);

    for (int i = 0; i < minLen; i++) {
        distance += Math.abs((s1.charAt(i) - 'a' + 1) - (s2.charAt(i) - 'a' + 1));
    }

    for (int i = minLen; i < len1; i++) {
        distance += (s1.charAt(i) - 'a' + 1);
    }
    for (int i = minLen; i < len2; i++) {
        distance += (s2.charAt(i) - 'a' + 1);
    }

    return distance;
}
