### ISSUE TITLE
Log Duplication

### ISSUE THREAD

**Issue by iejzh** [Codium-ai/cover-agent#53]
The UnitTestGenerator logs twice, a detailed log with timestamps and an abbreviated log without timestamps.
<img width="975" alt="截屏2024-05-27 10 57 56" src="https://github.com/Codium-ai/cover-agent/assets/32932199/471f3edc-1897-4582-af76-e21b95acdc5f">

**Comment by EmbeddedDevops1** [comment]
@iejzh I'm not seeing this issue on `main` anymore. Are you still seeing this?

**Comment by iejzh** [comment]
@EmbeddedDevops1  Yes, I can still see  this issue.

**Comment by EmbeddedDevops1** [comment]
How can I replicate it? Can you share the full command that you ran?

**Comment by iejzh** [comment]
The commands are as follows：
```
cover-agent \
  --source-file-path "templated_tests/python_fastapi/app.py" \
  --test-file-path "templated_tests/python_fastapi/test_app.py" \
  --code-coverage-report-path "templated_tests/python_fastapi/coverage.xml" \
  --test-command "pytest --cov=. --cov-report=xml --cov-report=term" \
  --test-command-dir "templated_tests/python_fastapi" \
  --coverage-type "cobertura" \
  --desired-coverage 70 \
  --max-iterations 10
```
The days of ***cover_agent.UnitTestGenerator*** are printed twice in the console output：
2024-06-03 14:24:28,452 - cover_agent.UnitTestGenerator - INFO - Running build/test command to generate coverage report: "pytest --cov=. --cov-report=xml --cov-report=term"
INFO:cover_agent.UnitTestGenerator:Running build/test command to generate coverage report: "pytest --cov=. --cov-report=xml --cov-report=term"

**Comment by EmbeddedDevops1** [comment]
@iejzh I was able to reproduce this but only by importing Cover agent as a pip package and running it against a completely different repo in debug mode using VSCode. Otherwise, I can't see the log duplication.

What's your environment set up? You ran this command straight after installing the pip package?
```
cover-agent \
  --source-file-path "templated_tests/python_fastapi/app.py" \
  --test-file-path "templated_tests/python_fastapi/test_app.py" \
  --code-coverage-report-path "templated_tests/python_fastapi/coverage.xml" \
  --test-command "pytest --cov=. --cov-report=xml --cov-report=term" \
  --test-command-dir "templated_tests/python_fastapi" \
  --coverage-type "cobertura" \
  --desired-coverage 70 \
  --max-iterations 10
```
