### ISSUE TITLE
How to use Azure openai endpoint with cover agent 

### ISSUE THREAD

**Issue by ajinkyapol** [Codium-ai/cover-agent#55]
I have saved 'AZURE_API_KEY', 'AZURE_API_BASE', 'AZURE_API_VERSION' as environment variables. When I run standalone litellm script using these variables it runs without error. But with cover agent it still looks for OPENAI_API_KEY.  What modification do i have to make.

**Comment by mrT23** [comment]
did you set the model as:
` model = "azure/<your deployment name>",             # model = azure/<your deployment name>`

?


https://docs.litellm.ai/docs/providers/azure#completion---using-azure_ad_token-api_base-api_version

**Comment by EmbeddedDevops1** [comment]
Closing issue. @ajinkyapol Please reopen if those instructions did not work for you. Thanks.
