### ISSUE TITLE
how to use in SpringBoot

### ISSUE THREAD

**Issue by liuzyong** [Codium-ai/cover-agent#65]
how to use in SpringBoot

**Comment by EmbeddedDevops1** [comment]
Hi. Could you please provide more context and/or detail in your issue?

**Comment by davidparry** [comment]
> how to use in SpringBoot

This [Docker image](https://hub.docker.com/repository/docker/davidparry/cover-agent-ubuntu-aarch64/general) gives the following [refactor-codium project](https://github.com/davidparry/refactor-codium/tree/cover-agent) Springboot example. If this helps?

**Comment by EmbeddedDevops1** [comment]
All Java-LLM specific issues should now be resolved. We have integrated two different types of Java projects in our [nightly regression tests as well](https://github.com/Codium-ai/cover-agent/blob/main/tests_integration/README.md).
