### ISSUE TITLE
use SpringBootTest has error

### ISSUE THREAD

**Issue by liuzyong** [Codium-ai/cover-agent#84]
PS F:\my-test> poetry run cover-agent `
>>   --source-file-path="src/main/java/com/cvicse/yzc/YzcController.java" `
>>   --test-file-path="src/test/java/com/cvicse/yzc/YzcControllerTest.java" `
>>   --code-coverage-report-path="target/site/jacoco/jacoco.csv" `
>>   --test-command="mvn test verify" `
>>   --test-command-dir="F:/my-test/cover-agent/templated_tests/backend-flow" `
>>   --coverage-type="jacoco" `
>>   --desired-coverage=70 `
>>   --max-iterations=10 `
>>   --model "ollama/qwen:72b" `
>>   --api-base "http://192.168.130.19:11434"
>> 
>>
http://192.168.130.19:11434"\x0a\x0a;d86617d3-11c1-4376-88ef-7e3475297894http://192.168.130.19:11434"\x0a\x0a;d86617d3-11c1-4376-88ef-7e34752978942024-06-05 17:56:55,031 - cover_agent.UnitTestGenerator - INFO - Running build/test command to generate coverage report: "mvn test verify"
2024-06-05 17:57:16,013 - cover_agent.UnitTestGenerator - WARNING - Error parsing coverage report: 'gbk' codec can't decode byte 0xae in position 1298: illegal multibyte sequence
2024-06-05 17:57:16,014 - cover_agent.UnitTestGenerator - INFO - Will default to using the full coverage report. You will need to check coverage manually for each passing test.

**Comment by liuzyong** [comment]
It is recommended that the operating file with encoding method
```
with open(self.file_path, 'r', encoding='utf-8')
```

**Comment by EmbeddedDevops1** [comment]
Hi. Can you post your test results file to the issue?

**Comment by EmbeddedDevops1** [comment]
All Java-LLM specific issues should now be resolved. We have integrated two different types of Java projects in our [nightly regression tests as well](https://github.com/Codium-ai/cover-agent/blob/main/tests_integration/README.md).
